### ISSUE TITLE
Cant compile to phone gap after install of plugin

### ISSUE THREAD

**Issue by knikolou** [techaffinity/freshchat-phonegap#26]
Dear i am getting this error when compile after freshchat install
my instalation is
a)<gap:plugin spec="https://github.com/techaffinity/freshchat-phonegap.git" source="git" />
b)document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() { 
window.Freshchat.init({
    	appId       : "xxxxxxxxxxxxxxxxxxxxx",
    	appKey      : "xxxxxxxxxxxxxxxxxxxx",
    });        

and the error

BUILD FAILED

Total time: 2.351 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by techaffinity** [comment]
Hi Knikolou
  
This conflict is due to com.google.android.gms:play-services-gcm  version with other plugins or it may due to your android version environment.

We recommend to install the plugin locally. 

Please download the plugin and change the required version of com.google.android.gms:play-services-gcm  in path ‘/src/android/Freshchat/build.gradle

Example :  compile 'com.google.android.gms:play-services-gcm:____’

Refer : https://developers.google.com/android/guides/setup

And install the plugin using command:

cordova plugin add “../local_pathtoPluginFolder/” 

Kindly let us know if you have any query.

Thanks.

**Comment by techaffinity** [comment]
We are not getting any feedback and we are closing this issue.
